name: utxorpc-haskell-client
version: 0.1.0.0
github: "githubuser/utxorpc-haskell-client"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

# extra-source-files:
# - README.md
# - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/utxorpc-haskell-client#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Client
    - Types
    - Logging
  dependencies:
    - http2-grpc-proto-lens
    - http2-grpc-types
    - http2-client-grpc
    - http2-client
    - proto-lens
    - proto-lens-protobuf-types
    - lens
    - utxorpc
    - bytestring
    - case-insensitive
    - uuid
    - katip
    - time
    - bytestring
