resolver: lts-22.7

packages:
  - client
  - server

extra-deps:
  # UTxO RCP codegen
  - utxorpc-0.0.5.0
  # >= 7.2.0 required to support FieldMasks
  - proto-lens-protobuf-types-0.7.2.1
  # required by proto-lens-protobuf-types, no version in snapshot
  - proto-lens-protoc-0.8.0.0
  # required by proto-lens-protobuf-types, no version in snapshot
  - proto-lens-setup-0.4.0.7
  # Hackage distribution has an overly-strict lower bound on `tls`,
  # which creates a conflict with `http2-grpc-haskell`
  - http2-client-0.10.0.1@sha256:58079887734eef615020b62a80d7b3053ac357cf5a359965d79aa6924f2501ce
  # Hackage distribution not up to date and creates build errors
  - git: https://github.com/haskell-grpc-native/http2-grpc-haskell.git
    commit: fb3b1150eb304ecb1ee588a588d7cff690ae809a
    subdirs:
      - http2-client-grpc # version in Hackage requires http2 >=1.6 && <2.1
      - http2-grpc-proto-lens # version in Hackage depends on an older version of bytestring
      - http2-grpc-types # version in Hackage depends on an older version of bytestring
      - warp-grpc # version in Hackage depends on older versions of bytestring, http2, and warp-tls
  # http2-5 in snapshot
  - http2-4.2.2
  # warp > 3.3.30 depends on http2 >= 5.0, incompatible with other libs
  - warp-3.3.30
  # required by proto-lens-protoc-0.8.0.0, no version in stackage
  - ghc-source-gen-0.4.4.1

nix:
  packages: [ protobuf, zlib ]  