name: utxorpc-haskell-server
version: 0.1.0.0
github: "githubuser/utxorpc-haskell-server"
license: Apache-2
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

# extra-source-files:
# - README.md
# - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/utxorpc-haskell-server#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Server
    - Build
    - Submit
    - Sync
    - Watch
    - Logging
  dependencies:
    - warp-grpc
    - utxorpc
    - http2-client
    - proto-lens
    - bytestring
    - lens
    - http2-grpc-proto-lens
    - http2-grpc-types
    - warp-tls
    - warp
    - wai
    - case-insensitive
    - time
    - io-streams
    - katip
    - transformers
    - uuid
    - text
    - aeson

executables:
  utxorpc-haskell-server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - utxorpc-haskell-server
      - katip
      - uuid
      - warp-grpc
      - utxorpc
      - proto-lens
      - lens
      - bytestring
      - wai
      - text
      - aeson
      - transformers
      - http2-grpc-types
      - warp
      - warp-tls
