name: "Release"

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: "Dry run"
        shell: bash
        run: |
          export HACKAGE_KEY=${{ secrets.HACKAGE_REGISTRY_TOKEN }}
          stack test
          stack haddock --haddock-for-hackage
          stack upload --candidate --test-tarball client server
          stack upload --candidate client server --documentation

      - name: "Publish"
        if: startsWith(github.ref, 'ref/tags/v')
        shell: bash
        run: |
          export HACKAGE_KEY=${{ secrets.HACKAGE_REGISTRY_TOKEN }}
          stack upload client server
          stack upload client server --documentation
