name: "Release"

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-hs
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Restore Stack
        id: restore-stack
        uses: actions/cache/restore@v4
        with:
          path: |
            ${{ steps.setup-hs.outputs.stack-root }}
            codegen/haskell/.stack-work
          key: stack-${{ hashFiles('stack.yaml.lock') }}
          restore-keys: stack-

      - name: "Dry run"
        shell: bash
        run: |
          export HACKAGE_KEY=${{ secrets.HACKAGE_REGISTRY_TOKEN }}
          stack test
          stack haddock --haddock-for-hackage
          stack upload --candidate --test-tarball client server
          stack upload --candidate client server --documentation

      - name: "Publish"
        if: startsWith(github.ref, 'ref/tags/v')
        shell: bash
        run: |
          export HACKAGE_KEY=${{ secrets.HACKAGE_REGISTRY_TOKEN }}
          stack upload client server
          stack upload client server --documentation

      - name: Cache Stack
        if: steps.restore-stack.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ${{ steps.setup-hs.outputs.stack-root }}
            codegen/haskell/.stack-work
          key: stack-${{ hashFiles('stack.yaml.lock') }}
